### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by specpropeller** [MailCore/mailcore2#524]
Build seems to be broken since commit 4a3761659ad94f2c447725c9dcc763241c8a7b2c.

Errors:
mailcore2/src/core/imap/MCIMAPSession.cc:2796:20: error: use of undeclared identifier 'mailimap_search_key_new_xgmraw'; did you mean 'mailimap_search_key_new_xgmthrid'?
            return mailimap_search_key_new_xgmraw(strdup(expression->value()->UTF8Characters()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mailcore2/src/core/imap/MCIMAPSession.cc:2796:51: error: cannot initialize a parameter of type 'uint64_t' (aka 'unsigned long long') with an rvalue of type 'char *'
            return mailimap_search_key_new_xgmraw(strdup(expression->value()->UTF8Characters()));
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
