### ISSUE TITLE
build error using Android NDK4.9 in Mac - must include typeinfo before using typeid

### ISSUE THREAD

**Issue by hongjingzhou** [MailCore/mailcore2#1528]
Build with Android NDK4.9 in Mac got error "must include typeinfo before using typeid"

ANDROID_PLATFORM=android-24
NDK_TOOLCHAIN_VERSION=4.9

[x86] Compile++      : MailCore <= com_libmailcore_Address.cpp
In file included from /mailcore2/build-android/jni/../../src/java/native/com_libmailcore_Address.cpp:3:0:
 /mailcore2/build-android/jni/../../src/java/native/com_libmailcore_Address.cpp: In function 'void initialize()':
 /mailcore2/build-android/jni/../../src/java/TypesUtils.h:117:63: error: must #include typeinfo before using typeid
         MCJNIRegisterNativeClass(&(typeid(mailcore::nativeType)), (ObjectToJavaConverter _) objectToJavaConverter); \
                                                               ^
 /mailcore2/build-android/jni/../../src/java/TypesUtils.h:23:24: note: in expansion of macro 'MC_JAVA_BRIDGE_internal'
 #define MC_JAVA_BRIDGE MC_JAVA_BRIDGE_internal(javaType, nativeType)
                        ^
 /mailcore2/build-android/jni/../../src/java/native/com_libmailcore_Address.cpp:107:1: note: in expansion of macro 'MC_JAVA_BRIDGE'
 MC_JAVA_BRIDGE
 ^
make: *_\* [/mailcore2/build-android/obj/local/x86/objs/MailCore//mailcore2/build-android/jni/**/**/src/java/native/com_libmailcore_Address.o] Error 1

**Comment by yuanlida** [comment]
I have solved this problem.You must download all dependicies and recompiled them.

**Comment by dinhviethoa** [comment]
It's fixed now.
